vich_uploader:
    db_driver: orm

    mappings:
       image:
           uri_prefix: /uploads/image
           upload_destination: '%kernel.project_dir%/public/uploads/image'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_remove: true
           delete_on_update: true